export const SET_ANIMES = 'SET_ANIMES';
export const TOGGLE_FAVORITE_ANIME = 'TOGGLE_FAVORITE_ANIME';
export const TOGGLE_STARRED_ANIME = 'TOGGLE_STARRED_ANIME';
export const TOGGLE_WATCHED_EPISODE = 'TOGGLE_WATCHED_EPISODE';
export const INITIALIZE_STARRED_ANIMES = 'INITIALIZE_STARRED_ANIMES';
export const INITIALIZE_FAVORITE_ANIMES = 'INITIALIZE_FAVORITE_ANIMES';
export const INITIALIZE_WATCHED_EPISODES = 'INITIALIZE_WATCHED_EPISODES';